package org.jhipster.task.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostsAllPropertiesEquals(Posts expected, Posts actual) {
        assertPostsAutoGeneratedPropertiesEquals(expected, actual);
        assertPostsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostsAllUpdatablePropertiesEquals(Posts expected, Posts actual) {
        assertPostsUpdatableFieldsEquals(expected, actual);
        assertPostsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostsAutoGeneratedPropertiesEquals(Posts expected, Posts actual) {
        assertThat(actual)
            .as("Verify Posts auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostsUpdatableFieldsEquals(Posts expected, Posts actual) {
        assertThat(actual)
            .as("Verify Posts relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getPublishedAt()).as("check publishedAt").isEqualTo(expected.getPublishedAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAuthorLogin()).as("check authorLogin").isEqualTo(expected.getAuthorLogin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostsUpdatableRelationshipsEquals(Posts expected, Posts actual) {
        // empty method
    }
}
